export enum PlaceholderConstants {
  LIST_SUBCOMMAND_GROUP_NAME = 'list',
  LIST_PLACEHOLDER_GROUPS_SUBCOMMAND_NAME = 'group',
  LIST_PLACEHOLDERS_SUBCOMMAND_NAME = 'placeholders',
  PLACEHOLDER_INFO_SUBCOMMAND_NAME = 'info',
}
